# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xl8LFwnJXuwEbksQpRGBLReXkT98wxsv
"""

++++++++++++++++++++++++++++++++++++++++++0
++++++++++
+++++++++++++++++++++++++++-!pip install vaderSentiment

import pandas as pd

# Load the dataset from 'train.csv'
df = pd.read_csv('train.csv')

# Clean column names (remove leading/trailing spaces)
df.columns = df.columns.str.strip()

# Manually update column names to more meaningful names
df.columns = ['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate', 'extra_column_1', 'extra_column_2']

# Ensure the dataset columns are numeric and clean non-numeric values
columns_of_interest = ['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']

# Convert columns to numeric and catch errors, coercing invalid values to NaN
for column in columns_of_interest:
    if column in df.columns:
        df[column] = pd.to_numeric(df[column], errors='coerce')

# Filter out rows where NaN appears in critical columns (toxic, severe_toxic)
df_cleaned = df.dropna(subset=['obscene', 'threat', 'insult', 'identity_hate'])

# Verify the data types after conversion and cleaning
print("Column types after cleaning:")
print(df_cleaned[columns_of_interest].dtypes)

# Get the class distribution for each of the valid columns
class_distribution = {}
for column in ['obscene', 'threat', 'insult', 'identity_hate']:
    if column in df_cleaned.columns:
        class_distribution[column] = df_cleaned[column].value_counts()

# Convert to a DataFrame for better visualization
class_distribution_df = pd.DataFrame(class_distribution)

# Output the class distribution
print("Class distribution for each column:")
print(class_distribution_df)

# Check the distribution for 'toxic' and 'severe_toxic' columns
toxic_severe_toxic_distribution = df[['toxic', 'severe_toxic']].dropna().apply(pd.Series.value_counts)
toxic_severe_toxic_distribution

import pandas as pd
import numpy as np
import re
from textblob import TextBlob
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.multioutput import MultiOutputClassifier
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
data = pd.read_csv("train.csv").sample(50000)

# Define target columns
target_columns = ['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']

# Initialize VADER Sentiment Analyzer
analyzer = SentimentIntensityAnalyzer()

# Text preprocessing function
def preprocess_text(text):
    text = text.lower()  # Convert to lowercase
    text = re.sub(r'http\S+|www\S+|https\S+', '', text)  # Remove URLs
    text = re.sub(r'\W+|\d+', ' ', text)  # Remove special characters and numbers
    text = re.sub(r'\s+', ' ', text).strip()  # Remove extra spaces
    return text

# Feature engineering function
def add_features(df):
    df['char_count'] = df['comment_text'].apply(len)
    df['word_count'] = df['comment_text'].apply(lambda x: len(x.split()))
    df['avg_word_length'] = df['char_count'] / (df['word_count'] + 1e-5)
    df['exclamation_count'] = df['comment_text'].apply(lambda x: x.count('!'))
    df['uppercase_ratio'] = df['comment_text'].apply(lambda x: sum(1 for c in x if c.isupper()) / len(x) if len(x) > 0 else 0)
    df['polarity'] = df['comment_text'].apply(lambda x: TextBlob(x).sentiment.polarity)
    df['subjectivity'] = df['comment_text'].apply(lambda x: TextBlob(x).sentiment.subjectivity)

    # VADER Sentiment Analysis Features
    df['vader_polarity'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['compound'])
    df['vader_neg'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['neg'])
    df['vader_neu'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['neu'])
    df['vader_pos'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['pos'])

    return df

# Preprocess text and engineer features
data['cleaned_comment'] = data['comment_text'].apply(preprocess_text)
data = add_features(data)

# TF-IDF vectorization
vectorizer = TfidfVectorizer(max_features=5000)
X_text = vectorizer.fit_transform(data['cleaned_comment'])

# Combine TF-IDF features with engineered features
X_features = data[['char_count', 'word_count', 'avg_word_length', 'exclamation_count',
                   'uppercase_ratio', 'polarity', 'subjectivity', 'vader_polarity',
                   'vader_neg', 'vader_neu', 'vader_pos']].values
scaler = MinMaxScaler()
X_features_scaled = scaler.fit_transform(X_features)

X_combined = np.hstack((X_text.toarray(), X_features_scaled))
y = data[target_columns]

# Train-test split (80:20 split)
X_train, X_test, y_train, y_test = train_test_split(X_combined, y, test_size=0.2, random_state=42)

# Train the model
rf = RandomForestClassifier(n_estimators=100, random_state=42)
model = MultiOutputClassifier(rf)
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Classification report
print("Classification Report:\n")
print(classification_report(y_test, y_pred, target_names=target_columns))

# Plot confusion matrix for each label
def plot_confusion_matrix(cm, labels, title):
    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=labels, yticklabels=labels)
    plt.title(title)
    plt.xlabel('Predicted')
    plt.ylabel('True')
    plt.show()

for i, label in enumerate(target_columns):
    cm = confusion_matrix(y_test.iloc[:, i], y_pred[:, i])
    print(f"Confusion Matrix for {label}:")
    plot_confusion_matrix(cm, ['Not Toxic', 'Toxic'], title=f"Confusion Matrix: {label}")

# Plot feature importance
def plot_feature_importance(model, feature_names):
    importances = model.feature_importances_
    indices = np.argsort(importances)[::-1]
    sorted_features = [feature_names[i] for i in indices[:20]]
    sorted_importances = importances[indices[:20]]

    plt.figure(figsize=(12, 6))
    plt.barh(sorted_features, sorted_importances, color='skyblue')
    plt.xlabel('Feature Importance')
    plt.title('Top 20 Feature Importances')
    plt.gca().invert_yaxis()
    plt.show()

# Extract feature names
feature_names = vectorizer.get_feature_names_out().tolist() + ['char_count', 'word_count', 'avg_word_length',
                                                               'exclamation_count', 'uppercase_ratio',
                                                               'polarity', 'subjectivity', 'vader_polarity',
                                                               'vader_neg', 'vader_neu', 'vader_pos']

# Plot feature importance for the first model in the MultiOutputClassifier
rf_model = model.estimators_[0]
plot_feature_importance(rf_model, feature_names)

import pandas as pd
import numpy as np
import re
from textblob import TextBlob
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.multioutput import MultiOutputClassifier
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
data = pd.read_csv("train.csv").sample(50000)

# Define target columns
target_columns = ['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']

# Initialize VADER Sentiment Analyzer
analyzer = SentimentIntensityAnalyzer()

# Text preprocessing function
def preprocess_text(text):
    text = text.lower()  # Convert to lowercase
    text = re.sub(r'http\S+|www\S+|https\S+', '', text)  # Remove URLs
    text = re.sub(r'\W+|\d+', ' ', text)  # Remove special characters and numbers
    text = re.sub(r'\s+', ' ', text).strip()  # Remove extra spaces
    return text

# Feature engineering function
def add_features(df):
    df['char_count'] = df['comment_text'].apply(len)
    df['word_count'] = df['comment_text'].apply(lambda x: len(x.split()))
    df['avg_word_length'] = df['char_count'] / (df['word_count'] + 1e-5)
    df['exclamation_count'] = df['comment_text'].apply(lambda x: x.count('!'))
    df['uppercase_ratio'] = df['comment_text'].apply(lambda x: sum(1 for c in x if c.isupper()) / len(x) if len(x) > 0 else 0)
    df['polarity'] = df['comment_text'].apply(lambda x: TextBlob(x).sentiment.polarity)
    df['subjectivity'] = df['comment_text'].apply(lambda x: TextBlob(x).sentiment.subjectivity)

    # VADER Sentiment Analysis Features
    df['vader_polarity'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['compound'])
    df['vader_neg'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['neg'])
    df['vader_neu'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['neu'])
    df['vader_pos'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['pos'])

    return df

# Preprocess text and engineer features
data['cleaned_comment'] = data['comment_text'].apply(preprocess_text)
data = add_features(data)

# TF-IDF vectorization
vectorizer = TfidfVectorizer(max_features=5000)
X_text = vectorizer.fit_transform(data['cleaned_comment'])

# Combine TF-IDF features with engineered features
X_features = data[['char_count', 'word_count', 'avg_word_length', 'exclamation_count',
                   'uppercase_ratio', 'polarity', 'subjectivity', 'vader_polarity',
                   'vader_neg', 'vader_neu', 'vader_pos']].values
scaler = MinMaxScaler()
X_features_scaled = scaler.fit_transform(X_features)

X_combined = np.hstack((X_text.toarray(), X_features_scaled))
y = data[target_columns]

# Train-test split (80:20 split)
X_train, X_test, y_train, y_test = train_test_split(X_combined, y, test_size=0.2, random_state=42)

# Train the model
rf = RandomForestClassifier(n_estimators=100,class_weight='balanced', random_state=42)
model = MultiOutputClassifier(rf)
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Classification report
print("Classification Report:\n")
print(classification_report(y_test, y_pred, target_names=target_columns))

# Plot confusion matrix for each label
def plot_confusion_matrix(cm, labels, title):
    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=labels, yticklabels=labels)
    plt.title(title)
    plt.xlabel('Predicted')
    plt.ylabel('True')
    plt.show()

for i, label in enumerate(target_columns):
    cm = confusion_matrix(y_test.iloc[:, i], y_pred[:, i])
    print(f"Confusion Matrix for {label}:")
    plot_confusion_matrix(cm, ['Not Toxic', 'Toxic'], title=f"Confusion Matrix: {label}")

# Plot feature importance
def plot_feature_importance(model, feature_names):
    importances = model.feature_importances_
    indices = np.argsort(importances)[::-1]
    sorted_features = [feature_names[i] for i in indices[:20]]
    sorted_importances = importances[indices[:20]]

    plt.figure(figsize=(12, 6))
    plt.barh(sorted_features, sorted_importances, color='skyblue')
    plt.xlabel('Feature Importance')
    plt.title('Top 20 Feature Importances')
    plt.gca().invert_yaxis()
    plt.show()

# Extract feature names
feature_names = vectorizer.get_feature_names_out().tolist() + ['char_count', 'word_count', 'avg_word_length',
                                                               'exclamation_count', 'uppercase_ratio',
                                                               'polarity', 'subjectivity', 'vader_polarity',
                                                               'vader_neg', 'vader_neu', 'vader_pos']

# Plot feature importance for the first model in the MultiOutputClassifier
rf_model = model.estimators_[0]
plot_feature_importance(rf_model, feature_names)

import pandas as pd
import numpy as np
import re
from textblob import TextBlob
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.multioutput import MultiOutputClassifier
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
import seaborn as sns
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping

# Load the dataset
data = pd.read_csv("train.csv").sample(50000)

# Define target columns
target_columns = ['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']

# Initialize VADER Sentiment Analyzer
analyzer = SentimentIntensityAnalyzer()

# Text preprocessing function
def preprocess_text(text):
    text = text.lower()
    text = re.sub(r'http\S+|www\S+|https\S+', '', text)
    text = re.sub(r'\W+|\d+', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

# Feature engineering function
def add_features(df):
    df['char_count'] = df['comment_text'].apply(len)
    df['word_count'] = df['comment_text'].apply(lambda x: len(x.split()))
    df['avg_word_length'] = df['char_count'] / (df['word_count'] + 1e-5)
    df['exclamation_count'] = df['comment_text'].apply(lambda x: x.count('!'))
    df['uppercase_ratio'] = df['comment_text'].apply(lambda x: sum(1 for c in x if c.isupper()) / len(x) if len(x) > 0 else 0)
    df['polarity'] = df['comment_text'].apply(lambda x: TextBlob(x).sentiment.polarity)
    df['subjectivity'] = df['comment_text'].apply(lambda x: TextBlob(x).sentiment.subjectivity)

    df['vader_polarity'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['compound'])
    df['vader_neg'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['neg'])
    df['vader_neu'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['neu'])
    df['vader_pos'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['pos'])

    return df

# Preprocess text and engineer features
data['cleaned_comment'] = data['comment_text'].apply(preprocess_text)
data = add_features(data)

# TF-IDF vectorization
vectorizer = TfidfVectorizer(max_features=5000)
X_text = vectorizer.fit_transform(data['cleaned_comment'])

# Combine TF-IDF features with engineered features
X_features = data[['char_count', 'word_count', 'avg_word_length', 'exclamation_count',
                   'uppercase_ratio', 'polarity', 'subjectivity', 'vader_polarity',
                   'vader_neg', 'vader_neu', 'vader_pos']].values
scaler = MinMaxScaler()
X_features_scaled = scaler.fit_transform(X_features)

X_combined = np.hstack((X_text.toarray(), X_features_scaled))
y = data[target_columns]

# Train-test split (80:20 split)
X_train, X_test, y_train, y_test = train_test_split(X_combined, y, test_size=0.2, random_state=42)

# Random Forest Model
rf = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)
rf_model = MultiOutputClassifier(rf)
rf_model.fit(X_train, y_train)

# Random Forest Predictions and Evaluation
y_pred_rf = rf_model.predict(X_test)
print("Random Forest Classification Report:\n")
print(classification_report(y_test, y_pred_rf, target_names=target_columns))

# Neural Network Model
input_dim = X_train.shape[1]  # Number of features

# Build the model
nn_model = Sequential([
    Dense(256, activation='relu', input_dim=input_dim),
    Dropout(0.3),
    Dense(128, activation='relu'),
    Dropout(0.3),
    Dense(len(target_columns), activation='sigmoid')  # Multi-label classification
])

# Compile the model
nn_model.compile(optimizer=Adam(learning_rate=0.001),
                 loss='binary_crossentropy',  # Suitable for multi-label classification
                 metrics=['accuracy'])

# Early stopping to prevent overfitting
early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

# Train the Neural Network
history = nn_model.fit(X_train, y_train,
                       epochs=20,
                       batch_size=64,
                       validation_split=0.2,
                       callbacks=[early_stopping],
                       verbose=1)

# Neural Network Predictions and Evaluation
y_pred_nn = nn_model.predict(X_test)
y_pred_nn = (y_pred_nn > 0.5).astype(int)  # Convert probabilities to binary predictions

print("Neural Network Classification Report:\n")
print(classification_report(y_test, y_pred_nn, target_names=target_columns))

# Plot model performance (Loss)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.show()

# Compare Models
print("\nComparison of Random Forest and Neural Network:\n")
rf_acc = np.mean([classification_report(y_test.iloc[:, i], y_pred_rf[:, i], output_dict=True)['accuracy'] for i in range(len(target_columns))])
nn_acc = np.mean([classification_report(y_test.iloc[:, i], y_pred_nn[:, i], output_dict=True)['accuracy'] for i in range(len(target_columns))])
print(f"Random Forest Average Accuracy: {rf_acc:.4f}")
print(f"Neural Network Average Accuracy: {nn_acc:.4f}")

!pip install scikeras
!pip install --upgrade scikit-learn scikeras
import sklearn
import tensorflow as tf
import scikeras

print("scikit-learn version:", sklearn.__version__)
print("tensorflow version:", tf.__version__)
print("scikeras version:", scikeras.__version__)

!pip install scikeras
!pip install --upgrade scikit-learn scikeras
!pip uninstall -y scikit-learn
!pip install scikit-learn==1.2.2


import pandas as pd
import numpy as np
import re
from textblob import TextBlob
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.metrics import classification_report
from sklearn.preprocessing import MinMaxScaler
from scikeras.wrappers import KerasClassifier
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam

# Load the dataset
data = pd.read_csv("train.csv").sample(50000)

# Define target columns
target_columns = ['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']

# Initialize VADER Sentiment Analyzer
analyzer = SentimentIntensityAnalyzer()

# Text preprocessing function
def preprocess_text(text):
    text = text.lower()
    text = re.sub(r'http\S+|www\S+|https\S+', '', text)
    text = re.sub(r'\W+|\d+', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

# Feature engineering function
def add_features(df):
    df['char_count'] = df['comment_text'].apply(len)
    df['word_count'] = df['comment_text'].apply(lambda x: len(x.split()))
    df['avg_word_length'] = df['char_count'] / (df['word_count'] + 1e-5)
    df['exclamation_count'] = df['comment_text'].apply(lambda x: x.count('!'))
    df['uppercase_ratio'] = df['comment_text'].apply(lambda x: sum(1 for c in x if c.isupper()) / len(x) if len(x) > 0 else 0)
    df['polarity'] = df['comment_text'].apply(lambda x: TextBlob(x).sentiment.polarity)
    df['subjectivity'] = df['comment_text'].apply(lambda x: TextBlob(x).sentiment.subjectivity)

    df['vader_polarity'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['compound'])
    df['vader_neg'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['neg'])
    df['vader_neu'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['neu'])
    df['vader_pos'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['pos'])

    return df

# Preprocess text and engineer features
data['cleaned_comment'] = data['comment_text'].apply(preprocess_text)
data = add_features(data)

# TF-IDF vectorization
vectorizer = TfidfVectorizer(max_features=5000)
X_text = vectorizer.fit_transform(data['cleaned_comment'])

# Combine TF-IDF features with engineered features
X_features = data[['char_count', 'word_count', 'avg_word_length', 'exclamation_count',
                   'uppercase_ratio', 'polarity', 'subjectivity', 'vader_polarity',
                   'vader_neg', 'vader_neu', 'vader_pos']].values
scaler = MinMaxScaler()
X_features_scaled = scaler.fit_transform(X_features)

X_combined = np.hstack((X_text.toarray(), X_features_scaled))
y = data[target_columns]

# Train-test split (80:20 split)
X_train, X_test, y_train, y_test = train_test_split(X_combined, y, test_size=0.2, random_state=42)

# Define Neural Network model
def build_model(hidden_layer1=256, hidden_layer2=128, dropout_rate=0.3, learning_rate=0.001):
    model = Sequential([
        Dense(hidden_layer1, activation='relu', input_dim=X_train.shape[1]),
        Dropout(dropout_rate),
        Dense(hidden_layer2, activation='relu'),
        Dropout(dropout_rate),
        Dense(len(target_columns), activation='sigmoid')  # Multi-label classification
    ])
    # Pass learning_rate to the Adam optimizer directly
    model.compile(optimizer=Adam(learning_rate=learning_rate),
                  loss='binary_crossentropy',
                  metrics=['accuracy'])
    return model

# Wrap the model for hyperparameter tuning
keras_clf = KerasClassifier(model=build_model, verbose=0)

# Hyperparameter grid
param_grid = {
    "model__hidden_layer1": [64, 128],  # Reduced hidden layer sizes
    "model__hidden_layer2": [32, 64],  # Reduced hidden layer sizes
    "model__dropout_rate": [0.3, 0.4],
    "model__learning_rate": [0.001, 0.0001],
    "batch_size": [32, 64],  # Reduced batch sizes
    "epochs": [10, 20]
}
# Randomized Grid Search
random_search = RandomizedSearchCV(estimator=keras_clf,
                                   param_distributions=param_grid,
                                   n_iter=10,  # Number of combinations to try
                                   cv=3,  # 3-fold cross-validation
                                   verbose=1,
                                   n_jobs=1)  # Use all CPUs

# Fit the Randomized Grid Search
random_search.fit(X_train, y_train)

# Best parameters
print(f"Best Parameters: {random_search.best_params_}")

# Evaluate on test set
best_nn_model = random_search.best_estimator_
y_pred_nn = best_nn_model.predict(X_test)
y_pred_nn = (y_pred_nn > 0.5).astype(int)  # Convert probabilities to binary predictions

# Classification Report for Neural Network
print("Neural Network Classification Report:\n")
print(classification_report(y_test, y_pred_nn, target_names=target_columns))

import pandas as pd
import numpy as np
import re
from textblob import TextBlob
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier  # Import for Random Forest
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.multioutput import MultiOutputClassifier
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam

# Load the dataset
data = pd.read_csv("train.csv").sample(50000)

# Define target columns
target_columns = ['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']

# Initialize VADER Sentiment Analyzer
analyzer = SentimentIntensityAnalyzer()

# Text preprocessing function
def preprocess_text(text):
    text = text.lower()  # Convert to lowercase
    text = re.sub(r'http\S+|www\S+|https\S+', '', text)  # Remove URLs
    text = re.sub(r'\W+|\d+', ' ', text)  # Remove special characters and numbers
    text = re.sub(r'\s+', ' ', text).strip()  # Remove extra spaces
    return text

# Feature engineering function
def add_features(df):
    df['char_count'] = df['comment_text'].apply(len)
    df['word_count'] = df['comment_text'].apply(lambda x: len(x.split()))
    df['avg_word_length'] = df['char_count'] / (df['word_count'] + 1e-5)
    df['exclamation_count'] = df['comment_text'].apply(lambda x: x.count('!'))
    df['uppercase_ratio'] = df['comment_text'].apply(lambda x: sum(1 for c in x if c.isupper()) / len(x) if len(x) > 0 else 0)
    df['polarity'] = df['comment_text'].apply(lambda x: TextBlob(x).sentiment.polarity)
    df['subjectivity'] = df['comment_text'].apply(lambda x: TextBlob(x).sentiment.subjectivity)

    # VADER Sentiment Analysis Features
    df['vader_polarity'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['compound'])
    df['vader_neg'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['neg'])
    df['vader_neu'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['neu'])
    df['vader_pos'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['pos'])

    return df

# Preprocess text and engineer features
data['cleaned_comment'] = data['comment_text'].apply(preprocess_text)
data = add_features(data)

# TF-IDF vectorization
vectorizer = TfidfVectorizer(max_features=5000)
X_text = vectorizer.fit_transform(data['cleaned_comment'])

# Combine TF-IDF features with engineered features
X_features = data[['char_count', 'word_count', 'avg_word_length', 'exclamation_count',
                   'uppercase_ratio', 'polarity', 'subjectivity', 'vader_polarity',
                   'vader_neg', 'vader_neu', 'vader_pos']].values
scaler = MinMaxScaler()
X_features_scaled = scaler.fit_transform(X_features)

X_combined = np.hstack((X_text.toarray(), X_features_scaled))
y = data[target_columns]

# Train-test split (80:20 split)
X_train, X_test, y_train, y_test = train_test_split(X_combined, y, test_size=0.2, random_state=42)

# Define the neural network model
def build_model(learning_rate, hidden_layer1, hidden_layer2, dropout_rate):
    model = Sequential()
    model.add(Dense(hidden_layer1, activation='relu', input_shape=(X_train.shape[1],)))
    model.add(Dropout(dropout_rate))
    model.add(Dense(hidden_layer2, activation='relu'))
    model.add(Dropout(dropout_rate))
    model.add(Dense(len(target_columns), activation='sigmoid'))
    model.compile(optimizer=Adam(learning_rate=learning_rate), loss='binary_crossentropy', metrics=['accuracy'])
    return model

# Best parameters from tuning
best_params = {
    'learning_rate': 0.0001,
    'hidden_layer1': 128,
    'hidden_layer2': 32,
    'dropout_rate': 0.4,
    'epochs': 20,
    'batch_size': 64
}

# Build and train the final model
final_model = build_model(
    learning_rate=best_params['learning_rate'],
    hidden_layer1=best_params['hidden_layer1'],
    hidden_layer2=best_params['hidden_layer2'],
    dropout_rate=best_params['dropout_rate']
)

history = final_model.fit(
    X_train,
    y_train,
    epochs=best_params['epochs'],
    batch_size=best_params['batch_size'],
    validation_data=(X_test, y_test),
    verbose=1
)

# Evaluate the model
y_pred_nn = (final_model.predict(X_test) > 0.5).astype(int)

# Generate classification report
print("Neural Network Classification Report:\n")
print(classification_report(y_test, y_pred_nn, target_names=target_columns))

# Compare with Random Forest
rf = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)
rf_model = MultiOutputClassifier(rf)
rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)
print("Random Forest Classification Report:\n")
print(classification_report(y_test, y_pred_rf, target_names=target_columns))

import matplotlib.pyplot as plt
import seaborn as sns

# Check the distribution of each target column
label_counts = data[target_columns].sum()

# Print the counts for each label
print("Class Imbalance Distribution:")
print(label_counts)

# Visualize the imbalance using a bar plot
plt.figure(figsize=(10, 6))
sns.barplot(x=label_counts.index, y=label_counts.values, palette="viridis")
plt.title("Class Imbalance Distribution")
plt.ylabel("Number of Samples")
plt.xlabel("Labels")
plt.xticks(rotation=45)
plt.show()

import pandas as pd
import numpy as np
import re
from textblob import TextBlob
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, roc_auc_score
from sklearn.multioutput import MultiOutputClassifier
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
from imblearn.over_sampling import SMOTE

# Load the dataset
data = pd.read_csv("train.csv").sample(50000, random_state=42)  # Use 50,000 samples

# Define target columns
target_columns = ['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']

# Initialize VADER Sentiment Analyzer
analyzer = SentimentIntensityAnalyzer()

# Text preprocessing function
def preprocess_text(text):
    text = text.lower()  # Convert to lowercase
    text = re.sub(r'http\S+|www\S+|https\S+', '', text)  # Remove URLs
    text = re.sub(r'\W+|\d+', ' ', text)  # Remove special characters and numbers
    text = re.sub(r'\s+', ' ', text).strip()  # Remove extra spaces
    return text

# Feature engineering function
def add_features(df):
    df['char_count'] = df['comment_text'].apply(len)
    df['word_count'] = df['comment_text'].apply(lambda x: len(x.split()))
    df['avg_word_length'] = df['char_count'] / (df['word_count'] + 1e-5)
    df['exclamation_count'] = df['comment_text'].apply(lambda x: x.count('!'))
    df['uppercase_ratio'] = df['comment_text'].apply(lambda x: sum(1 for c in x if c.isupper()) / len(x) if len(x) > 0 else 0)
    df['polarity'] = df['comment_text'].apply(lambda x: TextBlob(x).sentiment.polarity)
    df['subjectivity'] = df['comment_text'].apply(lambda x: TextBlob(x).sentiment.subjectivity)

    # VADER Sentiment Analysis Features
    df['vader_polarity'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['compound'])
    df['vader_neg'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['neg'])
    df['vader_neu'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['neu'])
    df['vader_pos'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['pos'])

    return df

# Preprocess text and engineer features
data['cleaned_comment'] = data['comment_text'].apply(preprocess_text)
data = add_features(data)

# TF-IDF vectorization
vectorizer = TfidfVectorizer(max_features=2000)  # Reduced features
X_text = vectorizer.fit_transform(data['cleaned_comment'])

# Combine TF-IDF features with engineered features
X_features = data[['char_count', 'word_count', 'avg_word_length', 'exclamation_count',
                   'uppercase_ratio', 'polarity', 'subjectivity', 'vader_polarity',
                   'vader_neg', 'vader_neu', 'vader_pos']].values
scaler = MinMaxScaler()
X_features_scaled = scaler.fit_transform(X_features)

X_combined = np.hstack((X_text.toarray(), X_features_scaled))
y = data[target_columns]

# Train-test split (80:20 split)
X_train, X_test, y_train, y_test = train_test_split(X_combined, y, test_size=0.2, random_state=42)

# Apply SMOTE for each label
smote = SMOTE(random_state=42)
X_resampled_list = []
y_resampled_list = []

for i, label in enumerate(target_columns):
    print(f"Resampling {label}...")
    X_resampled, y_resampled = smote.fit_resample(X_train, y_train[label])
    X_resampled_list.append(X_resampled)
    y_resampled_list.append(y_resampled)

# Combine resampled data
X_resampled = np.vstack(X_resampled_list)
y_resampled = np.vstack(y_resampled_list).T

# Define the neural network model
def build_model(learning_rate, hidden_layer1, hidden_layer2, dropout_rate):
    model = Sequential()
    model.add(Dense(hidden_layer1, activation='relu', input_shape=(X_resampled.shape[1],)))
    model.add(Dropout(dropout_rate))
    model.add(Dense(hidden_layer2, activation='relu'))
    model.add(Dropout(dropout_rate))
    model.add(Dense(len(target_columns), activation='sigmoid'))
    model.compile(optimizer=Adam(learning_rate=learning_rate), loss='binary_crossentropy', metrics=['accuracy'])
    return model

# Best parameters from tuning
best_params = {
    'learning_rate': 0.0001,
    'hidden_layer1': 128,
    'hidden_layer2': 32,
    'dropout_rate': 0.4,
    'epochs': 20,
    'batch_size': 64
}

# Build and train the final model
final_model = build_model(
    learning_rate=best_params['learning_rate'],
    hidden_layer1=best_params['hidden_layer1'],
    hidden_layer2=best_params['hidden_layer2'],
    dropout_rate=best_params['dropout_rate']
)

early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)
history = final_model.fit(
    X_resampled,
    y_resampled,
    epochs=best_params['epochs'],
    batch_size=best_params['batch_size'],
    validation_data=(X_test, y_test),
    callbacks=[early_stopping],
    verbose=1
)

# Evaluate the model
y_pred_nn = (final_model.predict(X_test) > 0.5).astype(int)

# Generate classification report
print("Neural Network Classification Report:\n")
print(classification_report(y_test, y_pred_nn, target_names=target_columns))

# Compare with Random Forest
rf = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)
rf_model = MultiOutputClassifier(rf)
rf_model.fit(X_resampled, y_resampled)
y_pred_rf = rf_model.predict(X_test)
print("Random Forest Classification Report:\n")
print(classification_report(y_test, y_pred_rf, target_names=target_columns))

import pandas as pd
import numpy as np
import re
from textblob import TextBlob
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, roc_auc_score
from sklearn.multioutput import MultiOutputClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.utils.class_weight import compute_class_weight
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Input
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping

# Load the dataset
data = pd.read_csv("train.csv").sample(30000, random_state=42)  # Use 30,000 samples to save memory

# Define target columns
target_columns = ['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']

# Initialize VADER Sentiment Analyzer
analyzer = SentimentIntensityAnalyzer()

# Text preprocessing function
def preprocess_text(text):
    text = text.lower()  # Convert to lowercase
    text = re.sub(r'http\S+|www\S+|https\S+', '', text)  # Remove URLs
    text = re.sub(r'\W+|\d+', ' ', text)  # Remove special characters and numbers
    text = re.sub(r'\s+', ' ', text).strip()  # Remove extra spaces
    return text

# Feature engineering function
def add_features(df):
    df['char_count'] = df['comment_text'].apply(len)
    df['word_count'] = df['comment_text'].apply(lambda x: len(x.split()))
    df['avg_word_length'] = df['char_count'] / (df['word_count'] + 1e-5)
    df['exclamation_count'] = df['comment_text'].apply(lambda x: x.count('!'))
    df['uppercase_ratio'] = df['comment_text'].apply(lambda x: sum(1 for c in x if c.isupper()) / len(x) if len(x) > 0 else 0)
    df['polarity'] = df['comment_text'].apply(lambda x: TextBlob(x).sentiment.polarity)
    df['subjectivity'] = df['comment_text'].apply(lambda x: TextBlob(x).sentiment.subjectivity)

    # VADER Sentiment Analysis Features
    df['vader_polarity'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['compound'])
    df['vader_neg'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['neg'])
    df['vader_neu'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['neu'])
    df['vader_pos'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['pos'])

    return df

# Preprocess text and engineer features
data['cleaned_comment'] = data['comment_text'].apply(preprocess_text)
data = add_features(data)

# TF-IDF vectorization
vectorizer = TfidfVectorizer(max_features=1000)  # Reduced features to save memory
X_text = vectorizer.fit_transform(data['cleaned_comment'])

# Combine TF-IDF features with engineered features
significant_features = ['char_count', 'word_count', 'avg_word_length', 'exclamation_count',
                        'uppercase_ratio', 'polarity', 'subjectivity', 'vader_polarity',
                        'vader_neg', 'vader_neu', 'vader_pos']
X_features = data[significant_features].values
scaler = MinMaxScaler()
X_features_scaled = scaler.fit_transform(X_features)

X_combined = np.hstack((X_text.toarray(), X_features_scaled))
y = data[target_columns]

# Train-test split (80:20 split)
X_train, X_test, y_train, y_test = train_test_split(X_combined, y, test_size=0.2, random_state=42)

# --------------------------- Neural Network Model ---------------------------
print("\nTraining Neural Network Model...")

# Compute class weights
class_weights = {}
for i, label in enumerate(target_columns):
    classes = np.unique(y_train[label])  # Convert to NumPy array
    weights = compute_class_weight('balanced', classes=classes, y=y_train[label])
    class_weights[i] = {0: weights[0], 1: weights[1]}

# Neural Network Architecture
def build_model(learning_rate, hidden_layer1, hidden_layer2, dropout_rate):
    model = Sequential()
    model.add(Input(shape=(X_train.shape[1],)))  # Explicit Input layer
    model.add(Dense(hidden_layer1, activation='relu'))
    model.add(Dropout(dropout_rate))
    model.add(Dense(hidden_layer2, activation='relu'))
    model.add(Dropout(dropout_rate))
    model.add(Dense(len(target_columns), activation='sigmoid'))
    model.compile(optimizer=Adam(learning_rate=learning_rate), loss='binary_crossentropy', metrics=['accuracy'])
    return model

# Best parameters from tuning
best_params = {
    'learning_rate': 0.0001,
    'hidden_layer1': 128,
    'hidden_layer2': 32,
    'dropout_rate': 0.4,
    'epochs': 20,
    'batch_size': 64
}

# Build and train the final model
final_model = build_model(
    learning_rate=best_params['learning_rate'],
    hidden_layer1=best_params['hidden_layer1'],
    hidden_layer2=best_params['hidden_layer2'],
    dropout_rate=best_params['dropout_rate']
)

# Convert class_weights to a format compatible with Keras
keras_class_weights = {}
for i, label in enumerate(target_columns):
    keras_class_weights[i] = class_weights[i][1]  # Use weight for class 1 (positive class)

early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)
history = final_model.fit(
    X_train,
    y_train,
    epochs=best_params['epochs'],
    batch_size=best_params['batch_size'],
    validation_data=(X_test, y_test),
    class_weight=keras_class_weights,  # Pass the corrected class weights
    callbacks=[early_stopping],
    verbose=1
)

# Evaluate the model
y_pred_nn = (final_model.predict(X_test) > 0.5).astype(int)

# Generate classification report
print("Neural Network Classification Report:\n")
print(classification_report(y_test, y_pred_nn, target_names=target_columns))

# --------------------------- Random Forest Model ---------------------------
print("\nTraining Random Forest Model...")

# Train Random Forest with class weights
rf = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)
rf_model = MultiOutputClassifier(rf)
rf_model.fit(X_train, y_train)

# Predict and evaluate Random Forest
y_pred_rf = rf_model.predict(X_test)
print("Random Forest Classification Report:\n")
print(classification_report(y_test, y_pred_rf, target_names=target_columns))

import pandas as pd
import numpy as np
import re
from textblob import TextBlob
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.multioutput import MultiOutputClassifier
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Input
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping

# Load the dataset
data = pd.read_csv("train.csv").sample(30000, random_state=42)  # Use 30,000 samples to save memory

# Define target columns
target_columns = ['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']

# Initialize VADER Sentiment Analyzer
analyzer = SentimentIntensityAnalyzer()

# Text preprocessing function
def preprocess_text(text):
    text = text.lower()  # Convert to lowercase
    text = re.sub(r'http\S+|www\S+|https\S+', '', text)  # Remove URLs
    text = re.sub(r'\W+|\d+', ' ', text)  # Remove special characters and numbers
    text = re.sub(r'\s+', ' ', text).strip()  # Remove extra spaces
    return text

# Feature engineering function
def add_features(df):
    df['char_count'] = df['comment_text'].apply(len)
    df['word_count'] = df['comment_text'].apply(lambda x: len(x.split()))
    df['avg_word_length'] = df['char_count'] / (df['word_count'] + 1e-5)
    df['exclamation_count'] = df['comment_text'].apply(lambda x: x.count('!'))
    df['uppercase_ratio'] = df['comment_text'].apply(lambda x: sum(1 for c in x if c.isupper()) / len(x) if len(x) > 0 else 0)
    df['polarity'] = df['comment_text'].apply(lambda x: TextBlob(x).sentiment.polarity)
    df['subjectivity'] = df['comment_text'].apply(lambda x: TextBlob(x).sentiment.subjectivity)

    # VADER Sentiment Analysis Features
    df['vader_polarity'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['compound'])
    df['vader_neg'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['neg'])
    df['vader_neu'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['neu'])
    df['vader_pos'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['pos'])

    return df

# Preprocess text and engineer features
data['cleaned_comment'] = data['comment_text'].apply(preprocess_text)
data = add_features(data)

# TF-IDF vectorization
vectorizer = TfidfVectorizer(max_features=1000)  # Reduced features to save memory
X_text = vectorizer.fit_transform(data['cleaned_comment'])

# Combine TF-IDF features with engineered features
significant_features = ['char_count', 'word_count', 'avg_word_length', 'exclamation_count',
                        'uppercase_ratio', 'polarity', 'subjectivity', 'vader_polarity',
                        'vader_neg', 'vader_neu', 'vader_pos']
X_features = data[significant_features].values
scaler = MinMaxScaler()
X_features_scaled = scaler.fit_transform(X_features)

X_combined = np.hstack((X_text.toarray(), X_features_scaled))
y = data[target_columns]

# Train-test split (80:20 split)
X_train, X_test, y_train, y_test = train_test_split(X_combined, y, test_size=0.2, random_state=42)

# --------------------------- Custom Undersampling ---------------------------
print("Applying custom undersampling to balance the dataset...")

# Function to undersample the majority class for a single label to the smallest size
def undersample_label(X, y, label, min_samples):
    # Separate positive and negative samples for the label
    positive_indices = np.where(y[label] == 1)[0]  # Use indices relative to the training data
    negative_indices = np.where(y[label] == 0)[0]

    # Undersample the negative class to match the minimum number of samples (positive samples or min_samples)
    negative_indices_undersampled = np.random.choice(negative_indices, size=min_samples, replace=False)

    # Combine positive and undersampled negative indices
    undersampled_indices = np.concatenate([positive_indices, negative_indices_undersampled])

    # Return the undersampled data
    return X[undersampled_indices], y.iloc[undersampled_indices]

# Find the smallest number of positive samples in any label
min_samples = min(y_train[target_columns].sum(axis=0))

# Apply undersampling to each label individually
X_resampled_list = []
y_resampled_list = []

for label in target_columns:
    print(f"Undersampling {label}...")
    X_resampled, y_resampled = undersample_label(X_train, y_train, label, min_samples)
    print(f"After undersampling {label}, X_resampled shape: {X_resampled.shape}, y_resampled shape: {y_resampled.shape}")
    X_resampled_list.append(X_resampled)
    y_resampled_list.append(y_resampled)

# Check the dimensions of X_resampled_list and y_resampled_list
print(f"Length of X_resampled_list: {len(X_resampled_list)}")
print(f"Length of y_resampled_list: {len(y_resampled_list)}")

# Ensure the number of samples in each resampled set are consistent
X_resampled = np.vstack(X_resampled_list)  # Stack all resampled features
y_resampled = np.vstack(y_resampled_list)  # Stack all resampled target labels

# Verify dimensions after stacking
print(f"After stacking, X_resampled shape: {X_resampled.shape}, y_resampled shape: {y_resampled.shape}")

# --------------------------- Random Forest Model ---------------------------
print("\nTraining Random Forest Model...")

# Train Random Forest with resampled data
rf = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)
rf_model = MultiOutputClassifier(rf)
rf_model.fit(X_resampled, y_resampled)

# Predict and evaluate Random Forest
y_pred_rf = rf_model.predict(X_test)
print("Random Forest Classification Report:\n")
print(classification_report(y_test, y_pred_rf, target_names=target_columns))

# --------------------------- Neural Network Model ---------------------------
print("\nTraining Neural Network Model...")

# Neural Network Architecture
def build_model(learning_rate, hidden_layer1, hidden_layer2, dropout_rate):
    model = Sequential()
    model.add(Input(shape=(X_resampled.shape[1],)))  # Explicit Input layer
    model.add(Dense(hidden_layer1, activation='relu'))
    model.add(Dropout(dropout_rate))
    model.add(Dense(hidden_layer2, activation='relu'))
    model.add(Dropout(dropout_rate))
    model.add(Dense(len(target_columns), activation='sigmoid'))
    model.compile(optimizer=Adam(learning_rate=learning_rate), loss='binary_crossentropy', metrics=['accuracy'])
    return model

# Best parameters from tuning
best_params = {
    'learning_rate': 0.0001,
    'hidden_layer1': 128,
    'hidden_layer2': 32,
    'dropout_rate': 0.4,
    'epochs': 20,
    'batch_size': 64
}

# Build and train the final model
final_model = build_model(
    learning_rate=best_params['learning_rate'],
    hidden_layer1=best_params['hidden_layer1'],
    hidden_layer2=best_params['hidden_layer2'],
    dropout_rate=best_params['dropout_rate']
)

early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)
history = final_model.fit(
    X_resampled,
    y_resampled,
    epochs=best_params['epochs'],
    batch_size=best_params['batch_size'],
    validation_data=(X_test, y_test),
    callbacks=[early_stopping],
    verbose=1
)

# Evaluate the model
y_pred_nn = (final_model.predict(X_test) > 0.5).astype(int)

# Generate classification report
print("Neural Network Classification Report:\n")
print(classification_report(y_test, y_pred_nn, target_names=target_columns))

!pip install nltk
!pip install textblob
!python -m nltk.downloader popular

import pandas as pd
import numpy as np
import re
from textblob import TextBlob
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.multioutput import MultiOutputClassifier
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Input
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
from imblearn.combine import SMOTEENN  # Hybrid sampling method
from sklearn.utils import shuffle


# --------------------------- Load the Dataset ---------------------------
data = pd.read_csv("train.csv").sample(30000, random_state=42)  # Use 30,000 samples for efficiency

# Define target columns
target_columns = ['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']

# Initialize VADER Sentiment Analyzer
analyzer = SentimentIntensityAnalyzer()

# --------------------------- Preprocessing ---------------------------
# Text preprocessing function
def preprocess_text(text):
    text = text.lower()  # Convert to lowercase
    text = re.sub(r'http\S+|www\S+|https\S+', '', text)  # Remove URLs
    text = re.sub(r'\W+|\d+', ' ', text)  # Remove special characters and numbers
    text = re.sub(r'\s+', ' ', text).strip()  # Remove extra spaces
    return text

# Feature engineering function
def add_features(df):
    df['char_count'] = df['comment_text'].apply(len)
    df['word_count'] = df['comment_text'].apply(lambda x: len(x.split()))
    df['avg_word_length'] = df['char_count'] / (df['word_count'] + 1e-5)
    df['exclamation_count'] = df['comment_text'].apply(lambda x: x.count('!'))
    df['uppercase_ratio'] = df['comment_text'].apply(lambda x: sum(1 for c in x if c.isupper()) / len(x) if len(x) > 0 else 0)
    df['polarity'] = df['comment_text'].apply(lambda x: TextBlob(x).sentiment.polarity)
    df['subjectivity'] = df['comment_text'].apply(lambda x: TextBlob(x).sentiment.subjectivity)

    # VADER Sentiment Analysis Features
    df['vader_polarity'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['compound'])
    df['vader_neg'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['neg'])
    df['vader_neu'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['neu'])
    df['vader_pos'] = df['comment_text'].apply(lambda x: analyzer.polarity_scores(x)['pos'])

    return df

# Preprocess text and engineer features
data['cleaned_comment'] = data['comment_text'].apply(preprocess_text)
data = add_features(data)

# TF-IDF vectorization
vectorizer = TfidfVectorizer(max_features=1000)  # Reduced features to save memory
X_text = vectorizer.fit_transform(data['cleaned_comment'])

# Combine TF-IDF features with engineered features
significant_features = ['char_count', 'word_count', 'avg_word_length', 'exclamation_count',
                        'uppercase_ratio', 'polarity', 'subjectivity', 'vader_polarity',
                        'vader_neg', 'vader_neu', 'vader_pos']
X_features = data[significant_features].values
scaler = MinMaxScaler()
X_features_scaled = scaler.fit_transform(X_features)

X_combined = np.hstack((X_text.toarray(), X_features_scaled))
y = data[target_columns]

# Train-test split (80:20 split)
X_train, X_test, y_train, y_test = train_test_split(X_combined, y, test_size=0.2, random_state=42)

# --------------------------- Combination of Oversampling and Undersampling ---------------------------
def resample_multilabel(X, y, smote_enn):
    """
    Resamples multilabel data using SMOTEENN for all labels simultaneously.
    Ensures binary labels in the output.
    """
    # Combine features and labels into a single dataset for consistent sampling
    combined = np.hstack((X, y.to_numpy()))  # Combine X and y into a single array

    # Apply SMOTEENN
    print("Applying SMOTEENN for multilabel data...")
    combined_resampled, _ = smote_enn.fit_resample(combined, y.sum(axis=1))  # Use label sum for SMOTEENN

    # Split the resampled dataset back into features and labels
    X_resampled = combined_resampled[:, :X.shape[1]]
    y_resampled = combined_resampled[:, X.shape[1]:]

    # Convert y_resampled back to binary (0 or 1)
    y_resampled = (y_resampled > 0.5).astype(int)

    return X_resampled, y_resampled

# Resample the training data
print("\nApplying SMOTEENN for each label...")
smote_enn = SMOTEENN(random_state=42)
X_resampled, y_resampled = resample_multilabel(X_train, y_train, smote_enn)

# Shuffle the resampled data
from sklearn.utils import shuffle
X_resampled, y_resampled = shuffle(X_resampled, y_resampled, random_state=42)

# Train Random Forest with the resampled data
rf = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)
rf_model = MultiOutputClassifier(rf)
rf_model.fit(X_resampled, y_resampled)

# Predict and evaluate Random Forest
y_pred_rf = rf_model.predict(X_test)
print("\nRandom Forest Classification Report:\n")
print(classification_report(y_test, y_pred_rf, target_names=target_columns))


# --------------------------- Random Forest Model ---------------------------
print("\nTraining Random Forest Model...")

# Train Random Forest with resampled data
rf = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)
rf_model = MultiOutputClassifier(rf)
rf_model.fit(X_resampled, y_resampled)

# Predict and evaluate Random Forest
y_pred_rf = rf_model.predict(X_test)
print("\nRandom Forest Classification Report:\n")
print(classification_report(y_test, y_pred_rf, target_names=target_columns))

# --------------------------- Neural Network Model ---------------------------
print("\nTraining Neural Network Model...")

# Neural Network Architecture
def build_model(learning_rate, hidden_layer1, hidden_layer2, dropout_rate):
    model = Sequential()
    model.add(Input(shape=(X_resampled.shape[1],)))  # Explicit Input layer
    model.add(Dense(hidden_layer1, activation='relu'))
    model.add(Dropout(dropout_rate))
    model.add(Dense(hidden_layer2, activation='relu'))
    model.add(Dropout(dropout_rate))
    model.add(Dense(len(target_columns), activation='sigmoid'))
    model.compile(optimizer=Adam(learning_rate=learning_rate), loss='binary_crossentropy', metrics=['accuracy'])
    return model

# Best parameters from tuning
best_params = {
    'learning_rate': 0.0001,
    'hidden_layer1': 128,
    'hidden_layer2': 32,
    'dropout_rate': 0.4,
    'epochs': 20,
    'batch_size': 64
}

# Build and train the final model
final_model = build_model(
    learning_rate=best_params['learning_rate'],
    hidden_layer1=best_params['hidden_layer1'],
    hidden_layer2=best_params['hidden_layer2'],
    dropout_rate=best_params['dropout_rate']
)

early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)
history = final_model.fit(
    X_resampled,
    y_resampled,
    epochs=best_params['epochs'],
    batch_size=best_params['batch_size'],
    validation_data=(X_test, y_test),
    callbacks=[early_stopping],
    verbose=1
)

# Evaluate the model
y_pred_nn = (final_model.predict(X_test) > 0.5).astype(int)

# Generate classification report
print("\nNeural Network Classification Report:\n")
print(classification_report(y_test, y_pred_nn, target_names=target_columns))

import numpy as np

# Save X_resampled and y_resampled
np.save("X_resampled.npy", X_resampled)
np.save("y_resampled.npy", y_resampled)

import pandas as pd

# Convert y_resampled to DataFrame
y_resampled_df = pd.DataFrame(y_resampled, columns=target_columns)

# Save X_resampled and y_resampled to CSV
np.savetxt("X_resampled.csv", X_resampled, delimiter=",")
y_resampled_df.to_csv("y_resampled.csv", index=False)

from sklearn.model_selection import GridSearchCV

param_grid = {
    'estimator__n_estimators': [50, 100],
    'estimator__max_depth': [10, 20],
    'estimator__min_samples_split': [2, 5]
}
grid_search = GridSearchCV(MultiOutputClassifier(RandomForestClassifier(random_state=42)), param_grid, cv=3, scoring='f1_micro')
grid_search.fit(X_resampled, y_resampled)
print("Best Parameters:", grid_search.best_params_)



!pip install keras-tuner
import keras_tuner as kt
import numpy as np

# Load X_resampled and y_resampled
X_resampled = np.load("X_resampled.npy")
y_resampled = np.load("y_resampled.npy")

def build_model(hp):
    model = Sequential()
    model.add(Input(shape=(X_resampled.shape[1],)))
    model.add(Dense(hp.Int('units_layer1', min_value=64, max_value=256, step=64), activation='relu'))
    model.add(Dropout(hp.Float('dropout_rate', min_value=0.1, max_value=0.5, step=0.1)))
    model.add(Dense(hp.Int('units_layer2', min_value=32, max_value=128, step=32), activation='relu'))
    model.add(Dense(len(target_columns), activation='sigmoid'))
    model.compile(optimizer=Adam(hp.Choice('learning_rate', [1e-2, 1e-3, 1e-4])), loss='binary_crossentropy', metrics=['accuracy'])
    return model

tuner = kt.RandomSearch(
    build_model,
    objective='val_loss',
    max_trials=10,
    executions_per_trial=1,
    directory='my_dir',
    project_name='nn_tuning'
)
tuner.search(X_resampled, y_resampled, epochs=10, validation_split=0.2)
best_hps = tuner.get_best_hyperparameters()[0]

import numpy as np

np.save("best_hps.npy", best_hps)

print(best_hps.get("units_layer1"))
print(best_hps.get("units_layer2"))
print(best_hps.get("learning_rate"))
print(best_hps.get("dropout_rate"))

from sklearn.metrics import classification_report, accuracy_score, roc_auc_score
# Build and train the neural network model model
final_model = tuner.hypermodel.build(best_hps)
history = final_model.fit(
    X_resampled, y_resampled,
    validation_split=0.2,
    epochs=20,
    batch_size=64,
    callbacks=[EarlyStopping(monitor='val_loss', patience=3)],
    verbose=1
)

# Evaluate the final model
y_pred_nn = (final_model.predict(X_test) > 0.5).astype(int)

# Print classification report
print("\nNeural Network Classification Report:\n")
print(classification_report(y_test, y_pred_nn, target_names=target_columns))

# Calculate total accuracy
accuracy = accuracy_score(y_test, y_pred_nn)
print(f"Total Accuracy: {accuracy:.4f}")

# Calculate AUC-ROC (assuming multi-class classification)
y_prob_nn = final_model.predict(X_test)  # Probability predictions
auc_roc = roc_auc_score(y_test, y_prob_nn, multi_class='ovr')  # Adjust for multi-class classification if needed
print(f"AUC-ROC: {auc_roc:.4f}")

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, roc_auc_score

# Initialize the Random Forest model with the best parameters
best_rf_model = RandomForestClassifier(
    max_depth=20,
    min_samples_split=2,
    n_estimators=100,
    random_state=42
)

# Fit the model to the resampled data
best_rf_model.fit(X_resampled, y_resampled)

# Evaluate the model (replace X_test and y_test with your test set)
y_pred = best_rf_model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")

# Print classification report
print("\nClassification Report:\n", classification_report(y_test, y_pred))

!pip install flask-ngrok
!pip install flask tensorflow scikit-learn nltk

# Save the trained model to a file
final_model.save('path_to_save_model/my_model.h5')  # Use .h5 or SavedModel format

# Load the saved model
import tensorflow as tf  # Import TensorFlow

# Load the saved model
model = tf.keras.models.load_model('my_model.h5') # Use tf.keras.models to access load_model function

model.summary()

import pickle
import json

# Save TfidfVectorizer
with open('tfidf_vectorizer.pkl', 'wb') as f:
    pickle.dump(vectorizer, f)

# Save Scaler
with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

# (Optional) Save SMOTEENN
with open('smoteenn.pkl', 'wb') as f:
    pickle.dump(smote_enn, f)

# Save Feature Engineering Configurations
preprocessing_config = {
    'target_columns': target_columns,
    'significant_features': ['char_count', 'word_count', 'avg_word_length', 'exclamation_count',
                             'uppercase_ratio', 'polarity', 'subjectivity', 'vader_polarity',
                             'vader_neg', 'vader_neu', 'vader_pos'],
    'max_sequence_length': 100
}
with open('preprocessing_config.json', 'w') as f:
    json.dump(preprocessing_config, f)

# Save Trained Neural Network Model
final_model.save('neural_network_model.h5')

print("All preprocessing objects and the trained model have been saved successfully!")